apiVersion: apps/v1
kind: Deployment
metadata:
  name: encontros-tech
  labels:
    app: encontros-tech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: encontros-tech
  template:
    metadata:
      labels:
        app: encontros-tech
    spec:
      containers:
      - name: encontros-tech
        image: fabricioveronez/encontros-tech:v1
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/encontrosdb"
---
apiVersion: v1
kind: Service
metadata:
  name: encontros-tech
  labels:
    app: encontros-tech
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: encontros-tech